name: Bug
description: Fehlerreport (reproduzierbar)
title: "[BUG] "
labels: [bug]
body:
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Was ist kaputt?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Repro Steps
      description: Schritt fuer Schritt
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected
  - type: textarea
    id: actual
    attributes:
      label: Actual
  - type: textarea
    id: evidence
    attributes:
      label: Evidence
      description: Logs/Screenshots/CI Link
