name: Feature
description: Feature/Enhancement
title: "[FEAT] "
labels: [enhancement]
body:
  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: Was soll am Ende anders sein?
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      placeholder: |
        - [ ]
        - [ ]
    validations:
      required: true
  - type: textarea
    id: constraints
    attributes:
      label: Constraints / Non-Goals
