name: Security
description: Security Finding (bitte sensibel)
title: "[SEC] "
labels: [security]
body:
  - type: textarea
    id: finding
    attributes:
      label: Finding
      description: Was wurde gefunden?
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Impact
  - type: textarea
    id: mitigation
    attributes:
      label: Mitigation
